/**
 * \file
 *
 * \brief Driver ISR.
 *
 (c) 2020 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include <driver_init.h>
#include <compiler.h>
#include "lin_driver.h"
#include "lin.h"

volatile uint16_t g_soft_timer_ticks;

ISR(USART4_RXC_vect)
{

	/**
	 * Insert your USART_0 reception complete interrupt handling code
	 *
	 * The interrupt flag will be cleared when the receive buffer is empty
	 * Otherwise interrupt flag can be cleared by writing 1 to its bit location
	 * in the STATUS register
	 */
	uint8_t index;
	/* 同步场错误*/
	index = (USART4.STATUS & USART_ISFIF_bm) >> USART_ISFIF_bp;
	if (index == 1)
	{
		LIN_DRV_IRQHandler(0,-1);
		USART4.STATUS |= USART_ISFIF_bm; /* 清除中断标志位*/
		return;
	}

	/* pid检验*/
	index = (USART4.RXDATAH & USART_DATA8_bm) >> USART_DATA8_bp;
	if (index == 0) /* is pid */
	{
		LIN_DRV_IRQHandler(0,1);
		USART4.STATUS |= USART_RXSIF_bm; /* 清除中断标志位*/
		return;
	}

	LIN_DRV_IRQHandler(0,0);
	//USART0.STATUS |= USART_RXCIF_bm; /* 清除中断标志位*/
}

ISR(TCA0_OVF_vect)
{
	/* Insert your TCA overflow interrupt handling code */

	/* The interrupt flag has to be cleared manually */
	TCA0.SINGLE.INTFLAGS = TCA_SINGLE_OVF_bm;
	g_soft_timer_ticks++;
	lin_lld_timeout_service(0);
}
